### ISSUE TITLE
breaks @rollup/plugin-node-resolve >= v7.1.0

### ISSUE THREAD

**Issue by yushijinhun** [yushijinhun/three-minifier#7]
```
$ npx rollup -c

index.js → dist/index.js...
[!] (plugin at position 1) TypeError: Cannot read property 'input' of undefined
TypeError: Cannot read property 'input' of undefined
    at /home/yushijinhun/repos/three-minifier/packages/rollup/node_modules/@rollup/plugin-node-resolve/dist/index.js:503:52
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/yushijinhun/repos/three-minifier/packages/rollup/node_modules/@rollup/plugin-node-resolve/dist/index.js:20:24)
    at _next (/home/yushijinhun/repos/three-minifier/packages/rollup/node_modules/@rollup/plugin-node-resolve/dist/index.js:42:9)
    at /home/yushijinhun/repos/three-minifier/packages/rollup/node_modules/@rollup/plugin-node-resolve/dist/index.js:49:7
    at new Promise (<anonymous>)
    at /home/yushijinhun/repos/three-minifier/packages/rollup/node_modules/@rollup/plugin-node-resolve/dist/index.js:38:12
    at Object.resolveId (/home/yushijinhun/repos/three-minifier/packages/rollup/node_modules/@rollup/plugin-node-resolve/dist/index.js:636:9)
    at Object.resolveId (/home/yushijinhun/repos/three-minifier/packages/rollup/build/plugin.js:402:47)
    at /home/yushijinhun/repos/rollup-demo/node_modules/rollup/dist/shared/rollup.js:18285:25
```

**Comment by yushijinhun** [comment]
This bug was introduced in @rollup/plugin-node-resolve v7.1.0 (https://github.com/rollup/plugins/commit/16d535510f77772c1ad91a1ee3862ee2e603a5a6)
